remote_theme: coursweb/jk-theme
title: Processus
description: Processus de design web.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Processus
   url: https://cours-web.ch/processus/
 - title: Créativité
   url: https://cours-web.ch/crea/

   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2018-2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/processus">Lien Github</a></li></ul>